version: '3.8'
services:
  web:
    build:
      context: ./
      target: production
    volumes:
      - .:/src
      - /src/node_modules
    command: npm run start
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
