version: '3.7'

services:
  node-app:
    container_name: node-app
    build:
      context: ./
      target: production
    volumes:
      - .:/src
      - /src/node_modules
      - /src/images
    command: npm run start
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 7890:8080
