name: AfterDeploy

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: cd /var/www/lucad.ml && docker-compose stop && docker-compose rm && docker-compose up -d --build
